@echo off

REM Remove intermediate files generated by Altium Designer in this directory and all subdirectories

echo Removing "__Previews" directories recursively
for /f "delims==" %%i in ('dir /ah /b /on /s "%~p0*__Previews"') do if "%%~ni"=="__Previews" rd "%%i" /s /q
echo.

echo Removing "History" directories recursively
for /f "delims==" %%i in ('dir /b /on /s "%~p0*History"') do if "%%~ni"=="History" rd "%%i" /s /q
echo.

echo Removing "Project Logs for *" directories recursively
for /f "delims==" %%i in ('dir /b /on /s "%~p0*Project Logs for *"') do rd "%%i" /s /q
echo.

echo Removing "*.PrjPcbStructure" files
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.PrjPcbStructure"') do del "%%i" /f /q
echo.

echo Removing "Status Report.Txt" files
for /f "delims==" %%i in ('dir /b /on /s "%~p0Status Report.Txt"') do del "%%i" /f /q
echo.

echo Removing "*.DRR" files
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.DRR"') do del "%%i" /f /q
echo.

echo Removing "*.LDP" files
for /f "delims==" %%i in ('dir /b /on /s "%~p0*.LDP"') do del "%%i" /f /q
echo.

echo "%~n0.bat" done.
